# fly.toml app configuration file generated for searchserver on 2023-07-11T17:12:11+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "searchserver"
primary_region = "hkg"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
